server:
  addr: ":3000"
  read_timeout: 10
  write_timeout: 10

database: 
  username: root
  password: ""
  host: 127.0.0.1
  port: 3306
  dbname: "chat_db"

redis:
  address: localhost:6379
  password: ""
  db: 0 

session:
  key: "2B7E151628AED2A6ABF7158809CF4F3C"
